### ISSUE TITLE
"Unknown variable $label" error during the generation

### ISSUE THREAD

**Issue by ibeketov** [adrianvlupu/C4-Builder#12]
Hello, I have an "Unknown variable $label" error during the generation of the diagram. It seems that something is wrong in the C4.plum $getPerson. Please see the attached screen.

How to reproduce:
- run c4builder new
- run c4builder
Result:
- no diagrams will be generated because of the error: https://ibb.co/Dzg81f0

**Comment by adrianvlupu** [comment]
Hi, this happens because of the PlantUML version.

Try to generate a diagram with only

```puml
@startuml
version
@enduml
```
Check the version. Most likely you are generating diagrams using the local jar file and the `latest` version of C4-PlantUML breaks because it supports the online plantuml server (1.2020.07).

Run config again and choose your version. Also, inside the diagrams, change the line
```
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/...
``` 

to

```
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/1.2019.09/...
```

**Comment by Whax** [comment]
Hi,

first thanks for your work. 

Unfortunately, I have the same problem here

```
plantuml -v
(0.000 - 481 Mo) 466 Mo - PlantUML Version 1.2020.07
```

```
@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/1.2020.07/C4_Container.puml
@enduml
```
![image](https://user-images.githubusercontent.com/5028767/81935651-44abfb00-95f1-11ea-91c2-5c84f6fe72c4.png)

**Comment by ibeketov** [comment]
> !include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/1.2019.09

Thank you @adrianvlupu  for your work and for help with the issue. 
The issue with a local rendering for plantuml v1.2019.09 was resolved by using the above-mentioned link. 
@Whax try to use the link above.
