### ISSUE TITLE
The c4-plantuml files in the adrianvlupu cause an error

### ISSUE THREAD

**Issue by kevinbader** [adrianvlupu/C4-Builder#8]
The template refers to https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml

When I use `c4builder new` and don't change anything I see this error:

![image](https://user-images.githubusercontent.com/1306829/80699534-69c24900-8adc-11ea-97a1-f658f76fb7e2.png)

With the c4-plantuml files from https://github.com/RicardoNiepel/C4-PlantUML it works (on both master and release-1-0 branches).

**Comment by zarathon** [comment]
I got the same issue here, to fix it, change my include to use previous version: **1.2019.09**
Just change ```latest```to use ```1.2019.09``` on include.

Sample
```!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/1.2019.09/C4_Deployment.puml```

**Comment by adrianvlupu** [comment]
Really sorry about this, all my projects broke when the plantuml server switched to 1.2020.07. I am working on a local version that downloads the c4-plantuml locally and let's you choose the plantuml version.

**Comment by adrianvlupu** [comment]
I have updated the project to use different versions of PlantUML and C4-Plantuml. This should make it easier to maintain if you generate the diagram images locally.

The original C4-PlantUML still works because even though https://plantuml.com/preprocessing states that

> You should not use `!define` and `!definelong` anymore. Use `!function`, `!procedure` or variable definition instead. `!define` should be replaced by return `!function` and `!definelong` should be replaced by `!procedure.`

since 2019, they never removed it. It's the main reason why that original repository was no longer updated.
